#create compendium
rrtools::use_compendium("../megafaunamap", open = FALSE)

#need to edit DESCRIPTION file

#create directories
dir.create("R")

dir.create("outputs")

dir.create("data")

dir.create("data/telemetry")

dir.create("outputs/poe_on_effort")

#declare package dependancies
# usethis::use_package("viridis")

#utiliser les pipes dans les fonctions
usethis::use_pipe()


#update NAMESPACE and add .Rd file for each function in man folder
devtools::document()

#load all functions
devtools::load_all()

#NB we have help page for each writen function automatically generated by roxygen skeleton
?osm_map

# Create the make.R to control the final rendering
file.create("make.R")

#command to stage files for git commit
git add -A
ls -al ~/.ssh

#uncommit
git reset --soft HEAD~1

#install all dependencies
remotes::install_deps(upgrade = "never")
